name: Daily RSS Aggregator

on:
  schedule:
    - cron: '0 6 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - openai_api_key: OPENAI_API_KEY
            openai_model: OPENAI_MODEL
            telegram_bot_token: TELEGRAM_BOT_TOKEN
            telegram_chat_id: TELEGRAM_CHAT_ID
            instructions: INSTRUCTIONS
            feed_urls: FEED_URLS
          - openai_api_key: OPENAI_API_KEY2
            openai_model: OPENAI_MODEL2
            telegram_bot_token: TELEGRAM_BOT_TOKEN2
            telegram_chat_id: TELEGRAM_CHAT_ID2
            instructions: INSTRUCTIONS2
            feed_urls: FEED_URLS2
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run the script
        env:
          OPENAI_API_KEY: ${{ secrets[matrix.openai_api_key] }}
          OPENAI_MODEL: ${{ secrets[matrix.openai_model] }}
          TELEGRAM_BOT_TOKEN: ${{ secrets[matrix.telegram_bot_token] }}
          TELEGRAM_CHAT_ID: ${{ secrets[matrix.telegram_chat_id] }}
          INSTRUCTIONS: ${{ secrets[matrix.instructions] }}
          FEED_URLS: ${{ secrets[matrix.feed_urls] }}
        run: python bot.py
